export const TICKET_WALLET_KEY = "splinter-states-ticket-wallet";
export const BASE_TICKETS = 500;

export const COUNTRY_NAMES: Record<string, string> = {
  USA: "United States",
  RUS: "Russia",
  CHN: "China",
  IND: "India",
  BRA: "Brazil",
  CAN: "Canada",
  MEX: "Mexico",
  GBR: "United Kingdom",
  FRA: "France",
  DEU: "Germany",
  ITA: "Italy",
  ESP: "Spain",
  PRT: "Portugal",
  NLD: "Netherlands",
  BEL: "Belgium",
  CHE: "Switzerland",
  AUT: "Austria",
  POL: "Poland",
  UKR: "Ukraine",
  TUR: "Turkey",
  IRN: "Iran",
  IRQ: "Iraq",
  SAU: "Saudi Arabia",
  PAK: "Pakistan",
  AFG: "Afghanistan",
  JPN: "Japan",
  KOR: "South Korea",
  PRK: "North Korea",
  IDN: "Indonesia",
  AUS: "Australia",
  ZAF: "South Africa",
  EGY: "Egypt",
  NGA: "Nigeria",
  ETH: "Ethiopia",
  ARG: "Argentina",
  CHL: "Chile",
  COL: "Colombia",
  PER: "Peru",
  VEN: "Venezuela",
  CUB: "Cuba",
  VNM: "Vietnam",
  THA: "Thailand",
  MMR: "Myanmar",
  KAZ: "Kazakhstan",

  // Custom missing territories
  ESB: "Eastern Sovereign Base Area",
  PSX: "Palestine",
  SDS: "South Sudan",
  SOL: "Somaliland",
  SAH: "Western Sahara",
  KOS: "Kosovo",
  USG: "Guantanamo Bay",
  CYN: "Northern Cyprus",
  KAS: "Kashmir",
  KAB: "Kabardino-Balkaria",
  WSB: "Western Sovereign Base Area",
  ALD: "Aland Islands",
  IOA: "Indian Ocean Territories",
  CSI: "Coral Sea Islands",
  PGA: "Spratly Islands",
  CLP: "Clipperton Island",
  ATC: "Ashmore and Cartier Islands",
};

export const FLAGS: Record<string, string> = {
  USA: "🇺🇸",
  RUS: "🇷🇺",
  CHN: "🇨🇳",
  IND: "🇮🇳",
  BRA: "🇧🇷",
  CAN: "🇨🇦",
  MEX: "🇲🇽",
  GBR: "🇬🇧",
  FRA: "🇫🇷",
  DEU: "🇩🇪",
  ITA: "🇮🇹",
  ESP: "🇪🇸",
  PRT: "🇵🇹",
  NLD: "🇳🇱",
  BEL: "🇧🇪",
  CHE: "🇨🇭",
  AUT: "🇦🇹",
  POL: "🇵🇱",
  UKR: "🇺🇦",
  TUR: "🇹🇷",
  IRN: "🇮🇷",
  IRQ: "🇮🇶",
  SAU: "🇸🇦",
  PAK: "🇵🇰",
  AFG: "🇦🇫",
  JPN: "🇯🇵",
  KOR: "🇰🇷",
  PRK: "🇰🇵",
  IDN: "🇮🇩",
  AUS: "🇦🇺",
  ZAF: "🇿🇦",
  EGY: "🇪🇬",
  NGA: "🇳🇬",
  ETH: "🇪🇹",
  ARG: "🇦🇷",
  CHL: "🇨🇱",
  COL: "🇨🇴",
  PER: "🇵🇪",
  VEN: "🇻🇪",
  CUB: "🇨🇺",
  VNM: "🇻🇳",
  THA: "🇹🇭",
  MMR: "🇲🇲",
  KAZ: "🇰🇿",

  // Custom missing territories
  ESB: "🇬🇧",
  PSX: "🇵🇸",
  SDS: "🇸🇸",
  SOL: "🇸🇴",
  SAH: "🇪🇭",
  KOS: "🇽🇰",
  USG: "🇺🇸",
  CYN: "🇹🇷",
  KAS: "🏔️",
  KAB: "⚑",
  WSB: "🇬🇧",
  ALD: "🇦🇽",
  IOA: "🇨🇨",
  CSI: "🇦🇺",
  PGA: "🏝️",
  CLP: "🇫🇷",
  ATC: "🇦🇺",
};

export const STRATEGIC_POWER: Record<string, number> = {
  USA: 110,
  CHN: 106,
  RUS: 98,
  IND: 90,
  BRA: 70,
  CAN: 66,
  AUS: 62,
  JPN: 60,
  DEU: 58,
  FRA: 56,
  GBR: 55,
  TUR: 50,
  IRN: 48,
  IDN: 48,
  MEX: 47,
  KOR: 45,
  SAU: 44,
  PAK: 43,
  ARG: 42,
  ZAF: 40,
  EGY: 39,
  NGA: 38,
  ITA: 38,
  ESP: 36,
  POL: 35,
  UKR: 35,
  KAZ: 34,
  COL: 32,
  ETH: 32,
  THA: 31,
  VNM: 31,
  MMR: 28,
  PER: 28,
  CHL: 26,
  VEN: 26,
  CUB: 22,
  ECU: 18,
};

export const MAP_COLORS = [
  "#2f5f8f", "#8e4f9f", "#2f7b4a", "#a66f2c", "#5f64a7", "#a34338",
  "#3d897c", "#897742", "#7a4f7f", "#4f7c9e", "#76934a", "#9a5a66",
  "#4d7350", "#8b6b3d", "#b4557a", "#528c5d", "#456fa3", "#a15d3a",
  "#6f5eb0", "#3f8f95", "#9b8045", "#8a5171", "#597d3f", "#386b74",
];

export const CONTINENT_OVERRIDES: Record<string, string> = {
  TUR: "Asia",
  IRN: "Asia",
  IRQ: "Asia",
  SYR: "Asia",
  JOR: "Asia",
  ISR: "Asia",
  LBN: "Asia",
  SAU: "Asia",
  YEM: "Asia",
  OMN: "Asia",
  ARE: "Asia",
  QAT: "Asia",
  KWT: "Asia",
  BHR: "Asia",
  ARM: "Asia",
  AZE: "Asia",
  GEO: "Asia",
  CYP: "Asia",
  RUS: "Europe",
  KAZ: "Asia",
  EGY: "Africa",

  // Custom missing territories
  ESB: "Asia",
  PSX: "Asia",
  SDS: "Africa",
  SOL: "Africa",
  SAH: "Africa",
  KOS: "Europe",
  USG: "North America",
  CYN: "Asia",
  KAS: "Asia",
  KAB: "Asia",
  WSB: "Asia",
  ALD: "Europe",
  IOA: "Asia",
  CSI: "Oceania",
  PGA: "Asia",
  CLP: "North America",
  ATC: "Asia",
};

export const REGION_OVERRIDES: Record<string, string> = {
  TUR: "Middle East",
  IRN: "Middle East",
  IRQ: "Middle East",
  SYR: "Middle East",
  JOR: "Middle East",
  ISR: "Middle East",
  LBN: "Middle East",
  SAU: "Middle East",
  YEM: "Middle East",
  OMN: "Middle East",
  ARE: "Middle East",
  QAT: "Middle East",
  KWT: "Middle East",
  BHR: "Middle East",
  ARM: "Middle East",
  AZE: "Middle East",
  GEO: "Middle East",
  PAK: "South Asia",
  AFG: "South Asia",
  IND: "South Asia",
  NPL: "South Asia",
  BGD: "South Asia",
  LKA: "South Asia",
  BTN: "South Asia",
  KAZ: "Central Asia",
  UZB: "Central Asia",
  TKM: "Central Asia",
  KGZ: "Central Asia",
  TJK: "Central Asia",
  CHN: "East Asia",
  MNG: "East Asia",
  JPN: "East Asia",
  KOR: "East Asia",
  PRK: "East Asia",
  VNM: "Southeast Asia",
  THA: "Southeast Asia",
  MMR: "Southeast Asia",
  LAO: "Southeast Asia",
  KHM: "Southeast Asia",
  MYS: "Southeast Asia",
  IDN: "Southeast Asia",
  PHL: "Southeast Asia",
  SGP: "Southeast Asia",
  EGY: "Northern Africa",

  // Custom missing territories
  ESB: "Middle East",
  PSX: "Middle East",
  SDS: "Eastern Africa",
  SOL: "Eastern Africa",
  SAH: "Northern Africa",
  KOS: "Southern Europe",
  USG: "Caribbean",
  CYN: "Middle East",
  KAS: "South Asia",
  KAB: "Central Asia",
  WSB: "Middle East",
  ALD: "Northern Europe",
  IOA: "Southeast Asia",
  CSI: "Australia and New Zealand",
  PGA: "Southeast Asia",
  CLP: "North America",
  ATC: "Southeast Asia",
};
